### ISSUE TITLE
[Question] Video from the lecture (from your PC)

### ISSUE THREAD

**Issue by KrisPetkov** [ivaylokenov/ASP.NET-Server-Architectures#2]
Will you upload the recorded video from your laptop somewhere?

**Comment by ivaylokenov** [comment]
Unfortunately, it does not have sound due to the microphone issues. You may watch the lecture in the first discussion post here: 
https://www.facebook.com/events/1241511809369108/permalink/1254137478106541/
It shows my computer screen so I guess it should be OK.
