### ISSUE TITLE
[Question] Startup vs Web and the relation between

### ISSUE THREAD

**Issue by KrisPetkov** [ivaylokenov/ASP.NET-Server-Architectures#3]
Hello, sorry to bother you again. I have few questions related to the Startup and Web projects and the relations between them:

Actually the Startup project is the real Asp.Net Core project (I mean it is displayed as such in Visual Studio, it does recognize the wwwroot folder, it can work with views... etc.). The Web project is a project (a DLL project) which is referencing the Microsoft.AspNetCore.App so it can work with Controllers. My question is: does referencing the Microsoft.AspNetCore.App enough to make this DLL project a fully functional replacement for the real Asp.Net project (in our case this is the Startup project)? And by fully functional I mean: working _Views_, _Components_, _Areas_ etc. - everything related and usable in a real Asp.Net project.

I'm asking because currently I have the following situation: 

![2020-02-10_15-45-18](https://user-images.githubusercontent.com/6774998/74155064-89a04a00-4c1c-11ea-8706-fc9ecef44e37.png)

**Note:** The red dashed line indicates the call to the DI registration of my services available in the Infrastructure layer. The Web project is my Composition Root containing the DI container and it calls all other layers to register their services. Nevertheless it is a dependency - the Web project depends to the Infrastructure project (only to call the registration of the services inside for the DI but it's a dependency).

That's why I'm asking the above question because I'm wondering how to get rid off this dependency. In your project you have the separate Web project (referencing the Microsoft.AspNetCore.App) but is it enough to replace the real Asp.Net Core project?

**Comment by KrisPetkov** [comment]
⬆️ @ivaylokenov 
Sorry if I'm annoying just wanted to ping you because I'm interested at this but couldn't find something appropriate on the internet.

**Comment by ivaylokenov** [comment]
Referencing the .App package is more than enough to make everything work. If Views cannot be found, you can separate them. I prefer to have a Startup application because then I would not have the dependency you are mentioning. It is a matter of opinion though, referencing the Infrastructure is still OK, if you do it only for DI purposes.

**Comment by KrisPetkov** [comment]
Thank you for the answer!
